export const testTypes = {
  SINGLE_ANSWER:'SINGLE_ANSWER',
    SINGLE_IMAGES_ANSWER:'SINGLE_IMAGES_ANSWER',
    MULTI_ANSWER:'MULTI_ANSWER',
    MULTI_IMAGES_ANSWER:'MULTI_IMAGES_ANSWER',
    BOOLEAN:'BOOLEAN',
    ACCORDANCE:'ACCORDANCE'

}